// Code generated by coz. DO NOT EDIT.
/**
 * Resources for site
 * @module the-site-resources
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get TheAliasResource () { return _d(require('./TheAliasResource')) },
  get TheHistoryResource () { return _d(require('./TheHistoryResource')) },
  get TheProfileResource () { return _d(require('./TheProfileResource')) },
  get TheRoleResource () { return _d(require('./TheRoleResource')) },
  get TheSignResource () { return _d(require('./TheSignResource')) },
  get TheTokenResource () { return _d(require('./TheTokenResource')) },
  get TheUserResource () { return _d(require('./TheUserResource')) },
}
